[program:dolcezampa_worker-product-images]
command=php /var/www/workdir/bin/worker-product-images
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0